### ISSUE TITLE
citing this code?

### ISSUE THREAD

**Issue by wcornwell** [schwilklab/taxon-name-utils#9]
Hi @dschwilk ,

Any thoughts on how to cite this code?  Maybe something like:  https://guides.github.com/activities/citable-code/?

**Comment by dschwilk** [comment]
I'll try to get that setup soon.

**Comment by dschwilk** [comment]
I used Zenodo as @wcornwell suggested.

DOI: 10.5281/zenodo.1067099 

[![DOI](https://zenodo.org/badge/20335477.svg)](https://zenodo.org/badge/latestdoi/20335477)

**Comment by wcornwell** [comment]
awesome!  thanks!
